export const BOOKS_LOADED = 'FETCH_BOOKS_SUCCESS';
export const BOOKS_REQUESTED = 'FETCH_BOOKS_REQUEST';
export const BOOKS_ERROR = 'FETCH_BOOKS_FAILURE';
export const BOOK_ADDED_TO_CART = 'BOOK_ADDED_TO_CART';